#!/usr/bin/env python3
"""
Portfolio用プロフェッショナル文書生成
技術アピール用にClient同等の正式文書を生成
"""

import os
import sys
import subprocess
from pathlib import Path
from datetime import datetime

# enhanced_client_document_generatorを流用
from enhanced_client_document_generator import ClientDocumentGenerator

class PortfolioDocumentGenerator(ClientDocumentGenerator):
    """Portfolio用にカスタマイズされた文書生成器"""

    def __init__(self, project_path="."):
        super().__init__(project_path)
        self.output_dir = Path(project_path) / "professional-docs"

    def generate_portfolio_documents(self):
        """Portfolio用の文書セットを生成"""
        print("📄 Portfolio用プロフェッショナル文書を生成中...")

        # 出力ディレクトリ作成
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # 各文書を生成（Markdown形式）
        documents = {
            "requirements-spec.md": self.generate_requirements_doc(),
            "design-spec.md": self.generate_basic_design(),
            "test-report.md": self.generate_test_report(),
            "user-manual.md": self.generate_user_manual()
        }

        # Markdownファイルを生成
        for filename, content in documents.items():
            filepath = self.output_dir / filename
            with open(filepath, 'w', encoding='utf-8') as f:
                # Portfolio用のヘッダーを追加
                header = f"""---
title: {filename.replace('.md', '').replace('-', ' ').title()}
project: {self.project_info.get('project', {}).get('name', 'Project')}
generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
ai_generated: true
---

# 📋 AI自動生成ドキュメント

> このドキュメントは、AIエージェントシステムにより自動生成されました。
> 実際の開発プロジェクトと同等の品質の文書を、わずか数秒で生成できることを実証しています。

---

"""
                f.write(header + content)
            print(f"  ✅ {filename}")

        # PDF変換を試みる
        self.convert_to_pdf_if_possible()

        # READMEを生成
        self.generate_docs_readme()

        return self.output_dir

    def convert_to_pdf_if_possible(self):
        """可能であればPDFに変換"""
        # pdf_converter.jsが利用可能か確認
        pdf_converter = Path(__file__).parent / "pdf_converter.js"

        if pdf_converter.exists() and (self.project_path / "node_modules" / "puppeteer").exists():
            print("  📄 PDFに変換中...")
            try:
                subprocess.run(
                    ["node", str(pdf_converter), str(self.output_dir)],
                    capture_output=True,
                    text=True,
                    timeout=30
                )
                print("  ✅ PDF変換完了")
            except Exception as e:
                print(f"  ⚠️ PDF変換スキップ: {e}")
        else:
            print("  ℹ️ PDF変換は利用できません（Markdown形式で保存）")

    def generate_docs_readme(self):
        """professional-docs用のREADME生成"""
        readme_content = f"""# 📚 プロフェッショナルドキュメント

## 概要

このディレクトリには、**実際の業務で使用されるレベルの正式文書**が含まれています。
すべての文書は**AIエージェントにより自動生成**されました。

## 含まれる文書

### 📋 要件定義書 (requirements-spec)
- プロジェクト概要
- 機能要件・非機能要件
- 制約事項
- 成果物定義

### 📐 基本設計書 (design-spec)
- システム構成
- アーキテクチャ設計
- データベース設計
- API仕様

### 🧪 テスト結果報告書 (test-report)
- テスト実施結果
- カバレッジ分析
- パフォーマンス測定
- 品質評価

### 📖 操作マニュアル (user-manual)
- インストール手順
- 使用方法
- トラブルシューティング
- FAQ

## 特徴

- ✅ **完全自動生成**: コードから必要な情報を抽出し、自動で文書化
- ✅ **プロフェッショナル品質**: 実際の業務で使用可能なレベル
- ✅ **PDF対応**: 印刷・配布可能な形式
- ✅ **日本語対応**: ビジネス文書として適切な日本語表現

## 生成時間

これらすべての文書は、AIエージェントにより**約1分**で生成されました。

## 技術的意義

このような包括的な文書セットを自動生成できることは、
**開発効率の大幅な向上**と**品質の標準化**を実現します。

---

Generated by AI Agent System @ {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""

        readme_path = self.output_dir / "README.md"
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)
        print("  ✅ README.md 生成完了")

def main():
    """Portfolio文書生成のメイン処理"""
    generator = PortfolioDocumentGenerator()
    output_dir = generator.generate_portfolio_documents()

    print(f"\n✅ Portfolio用文書生成完了！")
    print(f"📁 場所: {output_dir}")
    print("\nこれらの文書は、あなたの以下の能力を証明します：")
    print("  - AIを活用した自動化能力")
    print("  - プロフェッショナルな文書作成能力")
    print("  - 効率的なプロジェクト管理能力")

if __name__ == "__main__":
    main()